local GoldPath = {}

GoldPath["1000JINBI"]                   = "picdata/db_gold/1000jinbi.png"
GoldPath["100JINBI"]                    = "picdata/db_gold/100jinbi.png"
GoldPath["2000JINBI"]                   = "picdata/db_gold/2000jinbi.png"
GoldPath["200JINBI"]                    = "picdata/db_gold/200jinbi.png"
GoldPath["20JINBI"]                     = "picdata/db_gold/20jinbi.png"
GoldPath["300JINBI"]                    = "picdata/db_gold/300jinbi.png"
GoldPath["30JINBI"]                     = "picdata/db_gold/30jinbi.png"
GoldPath["5000JINBI"]                   = "picdata/db_gold/5000jinbi.png"
GoldPath["500JINBI"]                    = "picdata/db_gold/500jinbi.png"
GoldPath["50JINBI"]                     = "picdata/db_gold/50jinbi.png"
GoldPath["CARD1"]                       = "picdata/db_gold/card1.png"
GoldPath["CARD2"]                       = "picdata/db_gold/card2.png"
GoldPath["CARD3"]                       = "picdata/db_gold/card3.png"
GoldPath["CARD4"]                       = "picdata/db_gold/card4.png"
GoldPath["JB10"]                        = "picdata/db_gold/jb10.png"
GoldPath["JB100"]                       = "picdata/db_gold/jb100.png"
GoldPath["JB1000"]                      = "picdata/db_gold/jb1000.png"
GoldPath["JB18"]                        = "picdata/db_gold/jb18.png"
GoldPath["JB198"]                       = "picdata/db_gold/jb198.png"
GoldPath["JB30"]                        = "picdata/db_gold/jb30.png"
GoldPath["JB488"]                       = "picdata/db_gold/jb488.png"
GoldPath["JB50"]                        = "picdata/db_gold/jb50.png"
GoldPath["JB500"]                       = "picdata/db_gold/jb500.png"
GoldPath["JB6"]                         = "picdata/db_gold/jb6.png"
GoldPath["JB98"]                        = "picdata/db_gold/jb98.png"

return GoldPath