local RankPath = {}

RankPath[".DS_STORE"]                   = "picdata/rank/.DS_Store"
RankPath["BG_I_B"]                      = "picdata/rank/bg_i_b.png"
RankPath["BG_I_S"]                      = "picdata/rank/bg_i_s.png"
RankPath["BG_LIST"]                     = "picdata/rank/bg_list.png"
RankPath["BG_LIST_S"]                   = "picdata/rank/bg_list_s.png"
RankPath["BTN_PSF"]                     = "picdata/rank/btn_psf.png"
RankPath["BTN_SHARE"]                   = "picdata/rank/btn_share.png"
RankPath["HEADBGWOMEN"]                 = "picdata/rank/headBGWomen.png"
RankPath["HEADPICBGMAN"]                = "picdata/rank/headPicBGMan.png"
RankPath["JBS_ICON"]                    = "picdata/rank/jbs_icon.png"
RankPath["NO1"]                         = "picdata/rank/no1.png"
RankPath["POINT_DOWN"]                  = "picdata/rank/point_down.png"
RankPath["POINT_UP"]                    = "picdata/rank/point_up.png"
RankPath["PSF_ICON"]                    = "picdata/rank/psf_icon.png"
RankPath["RANK_LIST_BG"]                = "picdata/rank/rank_list_bg.png"
RankPath["RANK_NO_1"]                   = "picdata/rank/rank_no_1.png"
RankPath["RANK_NO_2"]                   = "picdata/rank/rank_no_2.png"
RankPath["RANK_NO_3"]                   = "picdata/rank/rank_no_3.png"
RankPath["RANK_NO_4"]                   = "picdata/rank/rank_no_4.png"
RankPath["RANKNOCHANGE"]                = "picdata/rank/rankNoChange.png"
RankPath["TITLE_PHB"]                   = "picdata/rank/title_phb.png"
RankPath["ZYL_ICON"]                    = "picdata/rank/zyl_icon.png"

return RankPath