local RewardPath = {}

RewardPath["ALREADY_SIGN_IN"]           = "picdata/reward/already_sign_in.png"
RewardPath["ALREADYSIGNIN"]             = "picdata/reward/alreadySignIn.png"
RewardPath["BTN_SIGN_IN"]               = "picdata/reward/btn_sign_in.png"
RewardPath["BTN_YQ"]                    = "picdata/reward/btn_yq.png"
RewardPath["DAY1"]                      = "picdata/reward/day1.png"
RewardPath["DAY2"]                      = "picdata/reward/day2.png"
RewardPath["DAY3"]                      = "picdata/reward/day3.png"
RewardPath["DAY4"]                      = "picdata/reward/day4.png"
RewardPath["DAY5"]                      = "picdata/reward/day5.png"
RewardPath["DAY6"]                      = "picdata/reward/day6.png"
RewardPath["DAY7"]                      = "picdata/reward/day7.png"
RewardPath["MENU_MZQD"]                 = "picdata/reward/menu_mzqd.png"
RewardPath["MENU_MZQD2"]                = "picdata/reward/menu_mzqd2.png"
RewardPath["MENU_RW"]                   = "picdata/reward/menu_rw.png"
RewardPath["MENU_RW2"]                  = "picdata/reward/menu_rw2.png"
RewardPath["REWARD_CELL_BIG"]           = "picdata/reward/reward_cell_big.png"
RewardPath["REWARD_CELL_SELECT"]        = "picdata/reward/reward_cell_select.png"
RewardPath["REWARD_CELL_SMALL"]         = "picdata/reward/reward_cell_small.png"
RewardPath["REWARDBG"]                  = "picdata/reward/rewardBg.png"
RewardPath["REWARDDIALOGBG"]            = "picdata/reward/rewardDialogBG.png"
RewardPath["SIGNLIGHT"]                 = "picdata/reward/signLight.png"
RewardPath["TASK_LIST_BG"]              = "picdata/reward/task_list_bg.png"
RewardPath["TIPS1"]                     = "picdata/reward/tips1.png"
RewardPath["TIPS2"]                     = "picdata/reward/tips2.png"
RewardPath["TITLE_REWARD"]              = "picdata/reward/title_reward.png"

return RewardPath