
if TRUNK_VERSION == DEBAO_TRUNK then
Lang_QuitRoom_Confirm		="离开后您已下注的金币将被扣除,确定要退出房间？"
Lang_BrokeProtect			="别灰心,你已获得新手保护 %d 金币,今天还有 %d 次机会."
Lang_BrokeprotectOver		="不好意思，您今天的新手保护金已经领完~明天还有免费金币可以领取哦~您也可以买点金币马上找他报仇哦."
Lang_QuickStartErrorNotEnoughMoney ="对不起，您的金币不足哟，充点金币换换手气吧!"
Lang_OldUserBankrupt			="对不起，您的金币不足哟，充点金币换换手气吧~"
Lang_FirstNotEnoughPlay		="您的账户余额不足,无法进入牌桌~去买点金币把~"
Lang_FirstNewBroken			="很遗憾,您已经没有新手保护金可以领了~想要继续游戏~去买点金币吧~"
Lang_FirstOldBroken			="对不起，您的金币不足哟~不要放过他。去买点金币复仇吧~"
Lang_FirstLessMinBuy		="您的账户余额不足本桌最小买入~去买点金币吧~"
Lang_NotEnoughChips			="您的金币不够了! 请及时充值"
Lang_MoreEnoughMoney		="您的金币超过了该房间的最大买入,建议更换到更大买入场游戏"
Lang_NotEnoughMoneyToPlayEmotion ="买入的钱不够了，赶紧补充金币吧！"
Lang_PROTECTED_ONETWO_PROMPT	="你的账户余额不足，系统赠送您%s金币,今天还剩    次机会."
Lang_PROTECTED_THREE_PROMPT		="你的账户余额不足，系统赠送您%s金币,今天机会已经用光了"
Lang_PROTECTED_MORE_PROMPT		="不好意思，您的新手保护金已经领完~明天还有免费金币可以领取哦"
Lang_Chip					="金币"
Lang_AUTO_BUYIN					="已为您自动买入金币"
Lang_LESS_MINBUYIN				="对不起，您的金币不够支付当前房间的最小买入。"
Lang_BANKRUPT_MINBUYIN			="对不起，您的金币不足哟，赶快充点金币再来玩吧!"
Lang_OnlySitCanBuyin		="请先坐下才能补充更多金币"
Lang_NotEnoughMoney			="不许耍流氓，想体验大场的刺激咱也要带够钱嘛，充点金币就可以立即与高手PK啦!"
else
Lang_QuitRoom_Confirm		="离开后您已下注的筹码将被扣除,确定要退出房间？"
Lang_BrokeProtect			="别灰心,你已获得新手保护 %d 筹码,今天还有 %d 次机会."
Lang_BrokeprotectOver		="不好意思，您今天的新手保护金已经领完~明天还有免费筹码可以领取哦~您也可以买点筹码马上找他报仇哦."
Lang_QuickStartErrorNotEnoughMoney ="对不起,您已经破产了，赶快充点筹码再来玩吧!"
Lang_OldUserBankrupt			="不好意思，您已经破产了，充点筹码再来玩吧~"
Lang_FirstNotEnoughPlay		="您的账户余额不足,无法进入牌桌~去买点筹码把~"
Lang_FirstNewBroken			="很遗憾,您已经没有新手保护金可以领了~想要继续游戏~去买点筹码吧~"
Lang_FirstOldBroken			="很遗憾,您已经破产了~不要放过他。去买点筹码复仇吧~"
Lang_FirstLessMinBuy		="您的账户余额不足本桌最小买入~去买点筹码吧~"
Lang_NotEnoughChips			="您的筹码不够了! 请及时充值"
Lang_MoreEnoughMoney		="您的筹码超过了该房间的最大买入,建议更换到更大买入场游戏"
Lang_NotEnoughMoneyToPlayEmotion ="买入的钱不够了，赶紧补充筹码吧！"
Lang_PROTECTED_ONETWO_PROMPT	="你的账户余额不足，系统赠送您%s筹码,今天还剩    次机会."
Lang_PROTECTED_THREE_PROMPT		="你的账户余额不足，系统赠送您%s筹码,今天机会已经用光了"
Lang_PROTECTED_MORE_PROMPT		="不好意思，您的新手保护金已经领完~明天还有免费筹码可以领取哦"
Lang_Chip					="筹码"
Lang_AUTO_BUYIN					="已为您自动买入筹码"
Lang_LESS_MINBUYIN				="对不起，您的筹码不够支付当前房间的最小买入。"
Lang_BANKRUPT_MINBUYIN			="对不起，您已经破产了，赶快充点筹码再来玩吧!"
Lang_OnlySitCanBuyin		="请先坐下才能补充更多筹码"
Lang_NotEnoughMoney			="不许耍流氓，想体验大场的刺激咱也要带够钱嘛，充点筹码就可以立即与高手PK啦!"
end

Lang_Button_Back            ="返回"
Lang_Title_Prompt			="温馨提示"
Lang_Login_Error_Prompt		="登录错误"
Lang_Button_Cancel			="取消"
Lang_Button_Quit			="退出"
Lang_Button_Confirm			="确认"
Lang_Button_Charge			="充值"
Lang_Button_Search			="查找"
Lang_Button_QuickStart		="快速开始"
Lang_Button_Relogin			="重新登录"
Lang_Error_Desc_Title		="错误提示:"
Lang_Error_Prompt_Title		="错误提示"
Lang_QuitMessage			="确定要退出游戏？"
Lang_QuitTourneyRoom_Confirm ="对不起，如果您现在返回大厅则视为主动弃权。"
Lang_Unkown_Error			="未定义错误,请刷新重连!"
Lang_NO_NETWORK				="您的网络不给力啊，请重新登录一下试试!"
Lang_ACCOUNT_ERROR			="您的帐号登录异常,请重新登录!"
Lang_ACCOUNT_LOGIN_AT_OTHER ="您的帐号在其他地方登录,请确认密码是否泄漏,请及时更新登录密码!"
Lang_REQUEST_DATA_ERROR		="请求数据出错,请重试!"
Lang_OTHER_ERROR			="其他错误!"
Lang_LOGIN_TIMEOUT			="登录超时,请重新登录"
Lang_SERVER_ERROR			="服务器人数太多,超出服务器可受连接限制"

Lang_WAITINGRUSHCanPlay		="正在加入新的牌桌"
Lang_NextHandCanPlay		="请等待下一局"
Lang_EmptyRoomWaitOthers    ="等待其他玩家进入"
Lang_SitErrorSeat			="错误的座位号"
Lang_SeatHasPlayer			="该座位有人请换其他座位"
Lang_AlreadyInTableSeat		="已经在该桌座位上"
Lang_CurrentRoundEndCanSit	="本轮牌局结束后才可座下"
Lang_NextRoundCanSit		="下一局才能坐下"
Lang_CurrentRoundEndBuyin   ="本轮牌局结束后自动帮你买入"
Lang_OnlySitCanChat			="坐下才能聊天或发表情"
Lang_QuickStartError		="快速开始查找座位失败!"
Lang_TableIdNotExist		="错误的房间,可能该房间已经不存在,请更换其他房间游戏!"
Lang_BuyinFail				="买入失败!"
Lang_CurrentRoomNotSeat		="当前房间没有空座位了"
Lang_NewerGuideSetWorkNext  ="新手引导设置将在下局生效"
Lang_LOGIN_ERROR_PROMPT		="网络有点忙，请稍候再试，感谢您对德堡的支持!"
Lang_NETWORK_NEED_AUTH      ="您的WIFI网络需要验证,请验证通过后再重新登录!"
Lang_SERVER_IS_UPDATING		="服务器升级维护中，请稍后再试, 感谢您对德堡的支持!"
Lang_USER_IS_LOCK		="该账户涉嫌违规，已被锁定"
Lang_TOURNEY_STATR				="锦标赛即将开始"
Lang_NEW_VERSION_PROMPT			="检查到有新版本,是否前往更新!"
Lang_BUTTON_CHARGENOW			="立即充值"
Lang_BUTTON_CHANGEROOM			="换个房间"
Lang_BUTTON_QUITEROOM			="退出房间"
Lang_LOGIN_USERNAMEORPASSWORD_ERROR	="用户名或密码错误，请重新登录。"
Lang_TOURISTTURN_SUCCESS		="恭喜您成功绑定德堡帐号！为了您的账户安全请重新登录。"
Lang_TOURISTTURN_SUCESS_ALIPAYOPEN	="恭喜您成功绑定德堡帐号！"
Lang_GAME_TECH_BREAK		="游戏教学还未结束，是否退出？"
Lang_GOTO_GAME_NOW		="立即游戏"
Lang_TECH_GAME_FINISH_REWARD_LEFT  ="恭喜您完成游戏教学，赠送您"
Lang_TECH_GAME_FINISH_REWARD_RIGHT  ="奖励，赶快去体验一下激烈的牌局吧。"
Lang_TECH_GAME_FINISH  ="恭喜您完成游戏教学，赶快去体验一下激烈的牌局吧。"
Lang_UPLOAD_IMAGE_MSG  ="尊敬的玩家：设置自定义图像涉及到上传头像，请确认您上传的头像是否符合国家相关规定，如果违反相关规定，责任将由个人承担。"


Lang_REBUY_ERROR_MORETHENINIT	="当前筹码大于初始筹码"
Lang_REBUY_ERROR_BLINDLEVEL		="当前牌局盲注级别大于合法重购值"
Lang_REBUY_ERROR_MAXCOUNT		="已达到最大重购次数"
Lang_REBUY_ERROR_FREQUENTLY		="请求重购过于频繁"
Lang_REBUY_ERROR_NOENOUGHMONEY	="重购余额不足"
Lang_REBUY_SCUESS				="重购成功"
Lang_REBUY_ERROR_OTHER			="重购失败。"
Lang_REBUY_ERROR_QIANQUAN		="已进入获奖范围,不能重购"
Lang_REBUY_ERROR_TIMEOUT		="很遗憾，您在规定时间未能复活成功，不能继续比赛。"
Lang_REBUY_ERROR_CLOSE			="很遗憾，您未选择复活，稍后将通知您比赛名次。"
Lang_REBUY_ERROR_MANULTIMEROUT	="很遗憾，您在规定时间未能购买成功，请继续比赛"

Lang_WRONG_ROOM_PASS_MSG  ="密码有误，请重新输入！"
Lang_Remind_User_Table_Will_Destroy ="温馨提示：该房间有效时间还有5分钟！"
Lang_Remind_User_Table_Card_Destroy ="温馨提示：本局结束后该房间将会关闭！"

lang_RECHARGE_NOTEXIT		="目前不支持此种数额的充值！"

lang_ADDFRIEND_FROMCONCERN		="加关注全新升级为加好友，请及时保留你关注的信息，方便进行查看"

lang_WECHATSHARE_TITLE		="德堡德州扑克"
lang_WECHATSHARE_FRIEND		="分享个好玩的游戏给你#德堡德州扑克#，快来感受下~~~~~~"

lang_WECHATSHARE_PROFIT_WIN1  ="我刚刚在#德堡德州扑克#赢了"
lang_WECHATSHARE_PROFIT_WIN2	="金币，快来和我切磋一下吧！最专业的德州扑克，我在德堡德州扑克等你"
lang_WECHATSHARE_PROFIT_FAILT1  ="我刚刚在#德堡德州扑克#竟然输了"
lang_WECHATSHARE_PROFIT_FAILT2  ="金币，小伙伴们感受下！"

lang_WECHATSHARE_TURNTABLE1   ="我在#德堡德州扑克#获得了"
lang_WECHATSHARE_TURNTABLE2   ="的奖励，大家快来看看吧！"

lang_WECHATSHARE_TOURNEY_SIGNUP   ="我在#德堡德州扑克#报名了 %s ,奖励丰厚，小伙伴们一起来吧。最专业的德州扑克，我在德堡德州扑克等你！"

lang_WECHATSHARE_FRIEND_GAME   ="我分享了＃德堡德州扑克＃朋友局 %s 账单，小伙伴们一起来吧。最专业的德州扑克，我在德堡德州扑克等你！"

lang_WECHATSHARE_RANK   ="我在#德堡德州扑克#的 %s 排名第 %s 名，快来和我切磋一下吧。最专业的德州扑克，我在德堡德州扑克等你！"

lang_WECHATSHARE_TOURNEY1   ="我在#德堡德州扑克#参加"
lang_WECHATSHARE_TOURNEY2   ="，好不容易拿了"
lang_WECHATSHARE_TOURNEY3   ="名，你们也去试试吧"

Lang_Login_NeedUpdate_Prompt ="版本过低"
lang_SNGPK_WIN		="恭喜您获得本场pk赛的胜利，您距离大奖很近了，赶快继续挑战吧！"
lang_SNGPK_LOSE		="战败！不要气馁，赶快继续挑战吧！"
lang_ROOMVIEW_BACKTOMAINVIEW	="返回大厅"
lang_ROOMVIEW_GOONPLAY			="继续挑战"