 PHPSESSID             ="PHPSESSID"
 YEAR                  ="year"
 MONTH                 ="month"
 CASH_CHIPS            ="cash_chips"
 CURRENT               ="current"
 LEFTTIME              ="left_time"
 GETUSERONLINECOUNT    ="getUserOnLineCount"
 GETSTARTEDTABLENUM    ="getStartedTableNum"
 GETACCOUNTINFO_POST   ="getAccountInfo"
 GETMYMILESTONEINFO    ="getMyMilestoneInfo"
 GETMYLEVELINFO        ="getMyLevelInfo"
 PWDCODE               ="code"
 PWDMSG                ="msg"
 TABLELIST			="TABLELIST"
 SERVER_TIME           ="SERVER_TIME"
 SYSTIME			  ="SYSTIME"
 PROCFG				="PROCFG"
 SERVERID			="SERVERID" --serverID for tencent proxy
 SERVERPORT			="SERVERPORT" --server port TGW
 UPDATE_CODE           ="UPDATE_CODE"
 USERCHANGE_PORTRAIT   ="USER_PORTRAIT"
 PAYEVENT              ="PAYEVENT"
 PAYAMOUNT			="PAYAMOUNT"
 PUSHPORT			="PUSHPORT"
 HAPPYHOURCONFIG		="HAPPYHOUR"
 TOURISTTURNCODE		="CODE"
 TOURISTTURNINFO		="info"
 TOURISTTURNMSG		="MSG"
 REGISTER_RESP_CODE	="REGISTER_RESP_CODE"
 DATA				="data"
 RESP				="RESP"
LOTTERY_URL = "LOTTERY_URL"
REWARD_URL = "REWARD_URL"
RWARD_STATUS = "RWARD_STATUS"

  LIST_DATA		="000F" --arraylist 请求列表
 CODE                  ="0001"  -- integer     操作（返回）码，对照表待定。。。
 SESSION_ID            ="0002"  -- string      session id
 HEADER                ="003"  -- hash(dict)  消息头
 BODY                  ="0004"  -- hash(dict)  消息体
 COMMAND_ID            ="0005"  -- integer     指令id
 CONNECT_ID            ="0006"  -- string      连接id
 TIMESTAMP             ="0007"  -- integer     unix时间戳
 SEQUENCE_ID           ="0008"  -- integer     本指令的序列号，每次RESP返回的序列号需要跟指令请求过来的序列号一致
 USER_AGENT            ="0009"  -- string      用户代理（客户端类型版本标识）
 CREATE_TIME           ="000A"  -- string      创建时间
 COMM_PROTO_VER        ="000B"  -- string      （指定后续数据的）通信协议版本号
 SEQUENCE              ="000D"  -- int         玩家牌桌内的操作的辨别标识
 VERSION="0011"	--string	--版本号
 LIST_REQUEST_TYPE     ="000E"	-- string  请求的列表类型



 TABLE_LIST            ="1001"  -- array(list) 牌桌清单
 TABLE_ID              ="1002"  -- string      牌桌id
 TABLE_TYPE            ="1003"  -- string      牌桌类型
 GAME_SPEED            ="1004"  -- integer     游戏速度
 BLIND_INFO            ="1005"  -- array(list) 盲注信息
 ANTE                  ="1006"  -- integer     底注
 TABLE_NAME            ="1007"  -- string      牌桌名称
 TABLE_INFO            ="1008"  -- hash(dict)  牌桌信息
 FROM_TABLE_ID         ="1009"  -- string      （牌桌重组后）来自哪个牌桌id
HALL_LIST_TYPE         ="100A"  --牌桌类型 //初级/中级/高级

BUYIN_TIMES				= "1011" -- string      #有效buyin次数统计

 PLAYER_LIST           ="2001"  -- array(list) 玩家清单
 SEAT_NUM              ="2002"  -- integer     座位数
 USER_ID               ="2003"  -- integer     用户id
 USER_NAME             ="2004"  -- string      用户名
 USER_CHIPS            ="2005"  -- integer     用户筹码
 HAND_ID               ="2006"  -- string     这一手的id（每一手都会有唯一的id）
 DEALER_BUTTON         ="2007"  -- integer     庄家
 SMALL_BLIND           ="2008"  -- integer     小盲
 BIG_BLIND             ="2009"  -- integer     大盲
 POT_INFO              ="200A"  -- array(list) 奖池信息
 COMMUNITY_CARDS       ="200B"  -- array(list) 公共牌
 BET_CHIPS             ="200C"  -- integer     下注（加注）筹码数
 ROUND_CHIPS           ="200D"  -- integer     这一圈（街）筹码数
 HAND_CHIPS            ="200E"  -- integer     这一手筹码数
 SEAT_NO               ="200F"  -- integer     座位编号
 GAME_STATUS           ="2010"  -- string      游戏状态
 PLAYER_STATUS         ="2011"  -- string      玩家状态
 REMAIN_TIME           ="2012"  -- integer     玩家剩余下注时间
 BUTTON_NO             ="2013"  -- integer     庄家位置
 SBLIND_NO             ="2014"  -- integer     小盲位置
 BBLIND_NO             ="2015"  -- integer     大盲位置
 WAIT_FOR_NO           ="2016"  -- integer     轮到下注者的座位号
 LAST_POTS             ="2017"  -- array(list) 上一街底池
 CARD_LIST             ="2018"  -- array(list) 牌的列表，亮牌的时候用
 PRIZE_LIST            ="2019"  -- array(list) 派奖list
 POT_RETURN            ="30B4"  -- dict 底池抽水返回
 ABSENT_LIST           ="201A"  -- array(list) 缺席（等待玩家）列表
 WAITING_LIST          ="201B"  -- array(list) 排队玩家列表
 POCKET_CARDS          ="201C"  -- array(list) 手牌
 REMOTE_NAME           ="201D"  -- string      远程服务名 ，就是目前的remotename，包括group_name,server_name
 HANDS_NUM             ="201E"  -- integer     打了多少手
 ANTE_INFO             ="201F"  -- array(list) 玩家下的底注信息
 CARD_TYPE             ="2020"  -- integer     牌型
 MAX_CARD              ="2021"  -- array(list) 最大的牌
 WIN_CHIPS             ="2022"  -- integer     赢得的筹码数
 OPTIONAL_ACTIONS      ="2023"  -- hash(dict)  可选的操作（行动）
 CALL                  ="2024"  -- integer     跟注（多少）
 RAISE                 ="2025"  -- array(list) 加注（下限和上限）
 IS_TRUSTEE            ="2026"  -- boolean     是否托管
 IS_AUTO_BLIND         ="2027"  -- boolean     是否自动缴纳盲注
 IS_AUTO_ANTE          ="2028"  -- boolean     是否自动缴纳底注
 PLAYER_MYINFO         ="2029"  -- hash(dict)  玩家自己的私有信息
 TOTAL_POT             ="202A"  -- integer     底池总额
 SHOWDOWN_OPTIONAL     ="202B"  -- boolean     是否可选择亮牌
 SHOWDOWN_TYPE         ="202C"  -- integer     亮牌类型
 RAKE_CHIPS            ="202D"  -- integer     抽水筹码数
 SITOUT_TIME           ="202E"  -- integer     玩家站起的时间
 AUTO_BLIND_TYPE       ="202F"  -- integer     设置玩家缴纳盲注类型
 NEW_BLIND_CHIPS       ="2030"  -- integer     新手盲注
 NEW_BLIND_INFO        ="2031"  -- hash(dict)  新手盲注缴纳信息
 BUY_CHIPS_MIN         ="2032"  -- integer     买入最小筹码数
 BUY_CHIPS_MAX         ="2033"  -- integer     买入最大筹码数
 RAKE_CHIPS_SUM_BF_FLOP="2034"  -- integer     翻牌前抽水筹码数
 RAKE_CHIPS_PER_BF_FLOP="2035"  -- integer     翻牌前额定每个玩家抽水筹码数
 RAKE_CHIPS_SUM_AF_FLOP="2036"  -- integer     翻牌后抽水筹码数
 RAKE_CHIPS_MAX_AF_FLOP="2037"  -- integer     翻牌后抽水最大筹码数
 RAKE_CHIPS_RATIO_AF_FLOP = "2038"  -- float       翻牌后抽水比例
 RAKE_INFO_BF_FLOP     ="2039"  -- hash(dict)  翻牌前抽水信息
 BUY_CHIPS             ="203A"  -- integer     买入筹码
 PLAYER_ID             ="203B"  -- integer     玩家（临时）ID
 PUNISH_BLIND_INFO     ="203C"  -- hash(dict)  惩罚盲注信息
 IS_PLAYING            ="203D"  -- boolean     是否玩的用户
 PUNISH_BLIND_CHIPS    ="203E"  -- integer     惩罚盲注大小
 BUY_TYPE              ="203F"  -- string      买入类型：BUY_IN或者RE_BUY
 CASH_OUT              ="2040"  -- integer     用户现金桌兑换的筹码数
 GAIN_POINTS           ="2041"  -- integer     用户现金桌获得的积分数
 STAY_TIME             ="2042"  -- integer     用户在牌桌上的待的持续时间
 BLIND_NAME            ="2043"  -- string      盲注名称
 RAKE_CHIPS_BF_FLOP    ="2044"  -- integer     翻牌前该玩家抽水筹码数
 RAKE_CHIPS_AF_FLOP    ="2045"  -- integer     翻牌后该玩家抽水筹码数
 HAND_START_REMAIN_TIME="2046"  -- integer     （下一手）牌局开始的剩余时间
 SBLIND_DODGE_NUM      ="2047"  -- integer     逃小盲次数
 BBLIND_DODGE_NUM      ="2048"  -- integer     逃大盲次数
 IS_NEW_PLAYER         ="2049"  -- boolean     是否新玩家（坐下了但还没进入牌局的）
 REWARD_INFO           ="204F"    --string  奖励信息
 QQ_SEX                ="2050"    --string QQ性别
 QQ_NAME               ="2051"    --string QQ name
 HeadPic_URL           ="4050"    --string QQ图像url
 PROFIT_MONEY		="2066"	 --string 房间盈利
 TOTAL_BUY_CHIPS		="2063"	--string 带进房间的筹码
APPLY_UID				="2075" --array(list) 申请人UID
APPLY_UNAME				="2076" --array(list) 申请人USERNAME
APPLY_DELAY_TIMES           = "2079"             --在当前街已经申请延时次数
KEEP_SEAT_STIME             = "2080"  --timestamp或者""

	IS_RE_BUY             ="309D"	  --是否是中途补充筹码 如果是 'YES'  不是中途补充筹码'NO'
--加好友
 CHANNEL_VISIABLE      ="30AB"	-- string  注册渠道可见"DEBAO,500WAN,BAIDU"
 OTHER_USER_ID		="2052"  --string 其他人的user id --加好友
 OTHER_USER_NAME		="2053"  --string 其他人的user name
 IS_AGREE			="2054"  --boolean 是否同意加为好友 1:同意 0：不同意
 MATCH_ID              ="3001"  -- integer     赛事ID
 MATCH_NAME            ="3002"  -- string      赛事名称
 MATCH_POINT			="504E"	--int		   赛事积分
 MATCH_TYPE            ="3003"  -- integer     赛事类型
 COMMON_RULE           ="3004"  -- integer     普通规则
 SPECIFIC_RULE         ="3005"  -- integer     特殊规则
 TOURNEY_TYPE          ="3006"  -- integer     锦标赛类型
 START_TIME            ="3007"  -- string      开始时间
 END_TIME              ="3008"  -- string      结束时间
 MATCH_STATUS          ="3009"  -- string      赛事状态
 MIN_UNUM              ="300A"  -- integer     最小开赛人数
 MAX_UNUM              ="300B"  -- integer     最大报名人数
 CUR_UNUM              ="300C"  -- integer     当前（已报名）人数
 PAY_INFO              ="300D"  -- string      报名支付信息
 USER_RANKING          ="300E"  -- integer     玩家排名
 CUR_TNUM              ="300F"  -- integer     当前牌桌数
 AWARDS                ="3010"  -- array(list) 奖品
 BLIND_LEVEL           ="3011"  -- integer     盲注等级
 PRIZE_NAME            ="3012"  -- string      奖品名称
 PRIZE_DESC            ="3013"  -- string      奖品描述
 PRIZE_BEGIN_RANK      ="3014"  -- integer     获奖人范围上限
 PRIZE_END_RANK        ="3015"  -- integer     获奖人范围下限
 PLAYERS_RANGE_MIN     ="3016"  -- integer     参赛人数范围上限
 PLAYERS_RANGE_MAX     ="3017"  -- integer     参赛人数范围下限
 RESOURCE_TYPE         ="3018"  -- string      资源组名
 PRIZE_POOL            ="3019"  -- integer     彩池
 INIT_CHIPS            ="301A"  -- integer     初始筹码
 WAITING_UNUM          ="301B"  -- integer     等待列表玩家人数
 ANNOUNCE_TIME         ="301C"  -- string      比赛通告时间
 REG_BEGIN_TIME        ="301D"  -- string      报名开始时间
 REG_DELAY_TIME        ="301E"  -- integer     延迟报名时间
 MIN_UCHIPS            ="301F"  -- integer     最低玩家筹码数
 MAX_UCHIPS            ="3020"  -- integer     最高玩家筹码数
 BLIND_TYPE            ="3021"  -- string      盲注类型
 REG_STATUS            ="3022"  -- integer     报名状态
 BLIND_DURATION        ="3023"  -- integer     升盲时间
 PRIZE_RULE            ="3024"  -- string      派奖（获奖）规则类型
 PRESET_START_TIME     ="3025"  -- string      预设开始时间
 PAY_TYPE              ="3026"  -- string      支付类型
 PAY_NUM               ="3027"  -- integer     支付数目
 SERVICE_CHARGE        ="3028"  -- integer     服务费
 BONUS_RATIO           ="3029"  -- float       奖池比例
 RETIRE_DEADLINE       ="302A"  -- string      退赛截止时间
 MATCH_NUMS            ="302B"  -- integer     赛事场次数
 APPLY_GOLD            ="302C"  -- integer     总的金币报名费
 APPLY_SILVER          ="302D"  -- integer     总的银币报名费
 APPLY_POINT           ="302E"  -- integer     总的积分报名费
 SERVICE_GOLD          ="302F"  -- integer     总的金币服务费
 SERVICE_SILVER        ="3030"  -- integer     总的银币服务费
 SERVICE_POINT         ="3031"  -- integer     总的积分服务费
 AUDIT_STATUS          ="3032"  -- string      赛事审核状态(YES/NO)
 BLIND_ID              ="3033"  -- integer     盲注结构ID
 BLIND_DESC            ="3034"  -- string      盲注描述
 PRIZE_ID              ="3035"  -- string      奖品订单ID（派奖ID）
 AWARD_ID              ="3036"  -- string      奖品ID
 BONUS_ID              ="3037"  -- integer     奖池分配id
 BONUS_NAME            ="3038"  -- string      奖池分配名
 BONUS_DESC            ="3039"  -- string      奖池描述
 INTHEMONEY_RATIO      ="303A"  -- integer     钱圈比例
 GAIN_ID               ="303B"  -- integer     物品奖励分配id
 GAIN_NAME             ="303C"  -- string      物品奖励分配名称
 GAIN_DESC             ="303D"  -- string      物品描述
 GAIN_TYPE             ="303E"  -- string      获取类型("DEBAO","SILVER" 等)
 GAIN_NUM              ="303F"  -- integer     活动数额
 GOODS_ID              ="3040"  -- integer     物品id
 AUDIT_BY              ="3041"  -- string      审核人
 MATCH_LEVEL           ="3042"  -- string      赛事级别
 MATCH_DESC            ="3043"  -- string      赛事描述
 FORCED_END_TIME       ="3044"  -- string      强制结束时间
 CAUTION_MONEY         ="3045"  -- string      奖池保证金
 GAME_ADDR             ="3046"  -- string      游戏地址
 PRIZE_STATUS          ="3047"  -- string      派奖状态
 WAITFOR_BIGBLIND_ENABLED="3048"  -- string      是否允许等待（轮到自己）大盲（才坐下打牌）
 REJOIN_CHIPS_TIME     ="3049"  -- integer     重新进入时间 在该时间范围内重新进入需要带入上次带离的筹码
 MAX_ENTRUST_TIMES     ="304A"  -- integer     托管时轮到大盲注的次数，超过该次数剔除用户
 MIN_TALBES            ="304B"  -- integer     现金桌配置类型最少牌桌数
 MAX_TABLES            ="304C"  -- integer     现金桌配置类型最大牌桌数
 GOODS_NAME            ="304D"  -- string      物品名称
 BONUS_NUM             ="304E"  -- float       奖金分配数目
 AWARD_DATE			="304F"  --	string	   获得奖励日期
 AWARD_STATUS		="3050"	--string		是否领奖
 AWARD_NUM			="3051"	--float			奖励数目
 ACTIVITY_ID			="3052"	--integer		活动id
 MIN_EXPERIENCE		="3053"	--float			经验值下限
 MAX_EXPERIENCE		="3054"	--float			经验值上限
 EXP_MILESTONE_YEAR	="3055"	--string		里程碑年
 AWARD_LIMIT_ID		="3056"	--integer		奖励资格id
 EXP_MILESTONE_ID	="3057"	--integer		里程碑id
 MATCH_COPY_CNT		="3058"	--integer		（赛事）补充拷贝的次数
 PLAYING_UNUM		="305A"	--integer		锦标赛未淘汰人数
 MATCH_INFO            ="3064"  --<array>list     赛事信息
 GAME_TYPE			="3065"  --string          游戏类型
 DISP_COLOR             ="3066"  --int          大厅展示牌桌的字体颜色
 KICK_OFFINE			="3068"	--string		 是否踢掉offline用户
 PICTURE_URL			="3063"  --string          活动图片ＵＲＬ
 TOURNEY_LEFTTIME	="306B"	--string		  锦标赛剩余时间
 IS_REBUYTOURNEY		="306C"	--string          是否是rebuy赛
 REBUY_LIMIT_COUNT	="306D"	--int			可成功rebuy的次数F
 LEGAL_BLIND_LEVEL	="306E"	--int			合法rebuy盲足级别
 REBUY_VALUE			="306F"	--double		rebuy一次增加的筹码
 REBUY_PAY_MONEY		="3071"	--double		rebuy一次的花费
 ADDON_WAIT_TIME       ="3072"	--integer  ADDON等待时间，单位s
 ADDON_VALUE           ="3073"	-- integer  addon买到的筹码量
 ADDON_PAYMONEY        ="3074"	-- integer  addon支付金额

 REBUY_COUNT			="2059"	--int			成功rebuy的次数
 PRIORITY			="3067"	--int			锦标赛展示优先级
 PASSIVE_REBUY_WAITTIME="3085"	--int			被动rebuy等待时间
 PASSIVE_REBUY_USER	="3075"	--array			被动rebuy玩家列表
 PLAYER_INIT_CHIPS	="3078"	--double		锦标赛玩家初始筹码
 REBUY_MODE			="3080"	--int			rebuy自动类型
 REBUY_TYPE			="3079"	--int			rebuy类型
 ADDON_START_TIME      ="3081"	-- integer  addon开始时间(unix时间戳
 REBUY_VALID_TIME      ="3082"	-- string  开赛后合法的rebuy时间
 TABLE_INIT_CHIPS	="100C"	--double		赛事开始玩家的初始筹码
 PLAY_TYPE			="30A5"	--string		玩牌类型
 TABLE_OWNER		      ="30A8"	--string		  房间属主 sys/user_id
 TOURNEY_MATCH_TYPE	="30B0"	--string		  锦标赛奖励类型
 TASK_ID               ="7005"  --int             任务ID
 TASK_TARGET           ="7006"  --array           完成任务所需总进度
 TASK_PROGRESS         ="7007"  --int             任务当前进度
 ACTIVITY_TITLE        ="7017"  --string          活动标题
 BTN_URL				="701A"  --string          活动按钮请求URL
 ACTIVITY_DESC		="7018"  --string          活动详细信息
 BTN_LABEL			="7019"  --string          活动按钮Label
 ACTIVITY_TIME		="701F"  --string		  活动时间
 BTN_STATUS			="702A"  --string		  按钮状态 NORMAL 正常可点 DISABLED 无效状态
 ACTIVITY_TAG       ="703A"  --活动跳转TAG
 
 TICKET_NUM            ="7015"--门票数量
 TICKET_MONEY          ="7011"--门票面额
 TICKET_TIME            ="7012"--门票有效期
 TICKET_TYPE            ="7010"--门票币种
 TICKET_GROUP		="7014"	--string		  门票类别
 TICKET_FLAG			="7016"	--string		  门票标记
 TICKET_ID			="700E"	--string		  门票id
 TICKET_NAME			="700F"	--string		  门票名称
 TASK_TITLE            ="7021"  --string          任务标题
 TASK_PRIZE            ="7022"  --array           任务奖励
 TASK_STATUS           ="7023"  --int             任务状态

 PLATFORM              ="4045"  -- string      平台
 PASSWORD              ="4001"  -- string      密码
 USER_TYPE             ="4002"  -- integer     用户类型
 USER_STATUS           ="4003"  -- string      用户状态
 MOD_TIME              ="4004"  -- string      （最后）修改时间
 BIRTHDAY              ="4005"  --string      出生日期
 USER_PORTRAIT         ="4006"  -- string      用户图像
 USER_PORTRAIT_TYPE    ="4007"  -- string      用户图像类型
 USER_REGTIME          ="4008"  -- string      注册时间
 USER_REGIP            ="4009"  -- string      注册PI
 LOGIN_IP              ="400A"  -- string      登录ip
 LOGIN_TIME            ="400B"  -- string      登录时间
 LOGIN_CHANNEL         ="400C"  -- string      渠道
 LOGIN_URL             ="400D"  -- string      登录url
 USER_EMAIL            ="400E"  -- string      用户邮箱
 USER_TRUENAME         ="400F"  -- string      用户真实名称
 USER_SEX              ="4010"  -- string      用户性别
 USER_COUNTRY          ="4011"  -- string      用户国家
 USER_PROVINCE         ="4012"  -- string      用户省份
 USER_CITY             ="4013"  -- string      用户所在市
 ADDRESS_DETAIL        ="4014"  -- string      用户地址详情
 USER_PHONE_NUMBER     ="4015"  -- string      用户手机号码
 CRT_TIME			="4016"  --  string      创建（添加）时间
 PORTRAIT_URL          ="4017"  -- string      头像图片url
 PASSWORD_LEVEL        ="4018"  -- string      密码强度
 CONTINUOUS_LOGIN_DAYS ="4019"  -- string      连续登录天数
 PORTRAIT_ICON		="401F" --string   头像图片id
 USER_QQ				="4043"  --string 用户QQ
 USER_NICKNAME		="403E"  --string 腾讯昵称
 MOBILE_ID			="403F"  --int    用户编号
 HAND_SUM			="4040"  --int    玩家玩牌总手数
 IS_IMAGE_CHARG        ="4051"  --聊天信息为图像表情,是否扣钱
 IMAGE_CHARG           ="4052"  --聊天信息为表情，扣的钱数目
 PRIVILEGE             ="4054"  --用户特权状态
 USER_LADDER_POINT     ="4055"  --升级后的牌手分
 USER_OLD_LADDER_POINT ="4057"--    升级前的牌手分
 USER_OLD_LEVEL        ="4058"--             升级前的等级
 CHARGE_ID             ="5001"  -- integer     账户充值流水ID
 BANK_ID               ="5002"  -- string      银行类型
 BANK_ORDER_ID         ="5003"  -- string      银行订单号
 ORDER_STATUS          ="5004"  -- string      订单状态
 CHARGE_TYPE           ="5005"  -- string      充值货币类型
 CHARGE_NUMBER         ="5006"  -- float       充值数量
 EXCHANGE_RATIO        ="5007"  -- float       汇率值
 MONEY_BALANCE         ="5008"  -- float       余额
 ADMIN_NAME            ="5009"  -- string      管理员（操作员）名称
 ADMIN_NOTE            ="500A"  -- string      管理（操作）说明
 ORDER_ID              ="500B"  -- integer     账务系统交易订单号
 USER_EXPERIENCE       ="500C"  -- string      用户经验
 USER_LEVEL            ="500D"  -- string      用户级别
 REMARK                ="500E"  -- string      备注
 ACCT_STATUS           ="500F"  -- string      账户状态
 ACCT_INOUT            ="5010"  -- string      账户出入类型
 ACCT_CUR_TYPE         ="5011"  -- string      货币类型
 BUSISORT              ="5012"  -- string      交易大类
 BUSINO                ="5013"  -- string      交易子类
 CHANNEL_ACCT          ="5014"  -- string      账户渠道
 TRANS_ORDER_ID        ="5015"  -- integer     外部交易订单号
 TRANS_MONEY           ="5016"  -- float       交易金额
 ORDER_CONTENT         ="5017"  -- string      订单备注
 ACCT_ID               ="5018"  -- integer     用户账户订单ID
 CUR_ORDERID           ="5019"  -- string      币种流水订单号
 TRANS_BALANCE         ="501A"  -- float       交易后剩余金额
 EXCHANGE_ID           ="501B"  -- integer     流水id
 EXCHANGE_RESOURCE     ="501C"  -- string      被兑换货币
 EXCHANGE_TARGET       ="501D"  -- string      兑换货币
 ADDTIME               ="501E"  -- string      添加时间
 CONFIG_TYPE           ="501F"  -- string      配置类型
 CONFIG_KEY            ="5020"  -- string      配置值
 CONFIG_VALUE          ="5021"  -- string      配置表达含义
 ACTUAL_MONEY          ="5022"  -- float       银行实际到账
 MODIFY_TYPE           ="5023"  -- string      修改对象（类型）
 MODIFY_VALUE          ="5024"  -- string      修改值
 MODIFY_IP             ="5025"  -- string      修改IP
 CONFIG_NAME           ="5026"  -- string      配置名称
 CONFIG_DESC           ="5027"  -- string      配置说明
 DEBAO_BALANCE         ="5028"  -- float       德堡币余额
 GOLD_BALANCE          ="5029"  -- float       金币余额
 SILVER_BALANCE        ="502A"  -- float       银币余额
 POINT_BALANCE         ="502B"  -- float       积分余额
 DIAMOND_BALANCE       ="5051"  -- float       钻石余额
 MOBILE_PIC_URL        ="30B3"  -- string   手机图片地址

 VIP_RANK              = "5052" --string vip当前充值额度
 NEXT_VIP_RANK         = "5053" --string 升级所需充值数

 CHARGE_UP_URL         ="502C"  -- string      充值的引导页面url
 CHARGE_DOWN_URL       ="502D"  -- string      充值成功后的提示页面url
 TRADE_TYPE            ="502E"  -- string      充值类型
 PAY_CHANNEL           ="502F"  -- string      充值渠道
 DEBAO_NUM             ="5030"  -- float       充值的德堡币数量
 REWARD_ID             ="5039"     --string      领取资格id
  REWARD_NUM			="503A"    --float       领取金额
  IS_REWARDED		="503B"      --bool      是否已领取
 NEED_NOTICE           ="6001"  -- string      是否（需要）关注（提醒）
 CREATE_ADMIN          ="6002"  -- string      创建人
 BULLETIN_ID           ="6003"  -- integer     公告ID
 CONTENT               ="6004"  -- string      (信息)内容


 NOTICE_TYPE			="6008"
 NOTICE_TITLE		="6009"
 NOTICE_CONTENT        ="600A"
 NOTICE_IS_PUBLIC      ="600B"
 NOTICE_IS_READED	="600C"
 NO_READ_NUM           ="600D"
 DSCRIPTION			="600E"	--string		  领奖返回描述
 NO_READ_TYPE          ="6008"
 CREATE_TIME	          ="000A"
 EXPIRE_TIME	          ="000C"
 NOTICE_DATE			="000D"
 UPDATE_URL			="0012" --string 更新包的URL
 FREQUENCE_LIMIT		="7003"  --int           参加活动频率限制
 SILVER_LIMIT          ="7002"  --int           银币的余额限制
 REWARDS_TIMES         ="7001"   --int          已领奖次数
 TIMES                 ="700C"   -- int 次数
 BTN_IMAGE			="701B"	--integer		活动按钮图片Image
 LIMIT_KEY             ="700D"   --活动资格限定key
 TASK_NODE_NEXT        ="7024"   --object       下一个任务节点的信息
 TIPS                  ="702C"  --提示信息
 ACTIVITY_BG		   = "703C" --活动背景
 ACTIVITY_NAME         = "703D" --活动名字
 ACTIVITY_LABEL        = "703B" --活动按钮名字    
--analysis
 STAT_KEY_VPIP         ="8001" --object 入局率
  STAT_KEY_PFR         ="8002"--object  翻牌前加注率
  STAT_KEY_BB100       ="8010"	--array	每100手牌，玩家平均赢或者输的大盲注数量
 STAT_KEY_WINNING      ="8011"--object 总输赢金额
 STAT_KEY_HANDS        ="8012"--object 局数
 STAT_KEY_AF           ="800A"--object 游戏激进度
 STAT_KEY_COLOR        ="8013"--string 颜色
 STAT_KEY_VALUE        ="8014"--string 数值
 STAT_KEY_PRECISION    ="801B"--string 牌谱分析精度位数
 REPORT_FIRST_TIME	="8016" --玩家第一手牌的发生日期
 REPORT_TOTAL_POINT	="8017" --取样总点数量
 REPORT_BIG_PRECISION="8018"  --横坐标精度（大格数）
 REPORT_SMALL_PRECISION="8019" --横坐标精度（小格数）
 REPORT_TOTAL_DAYS	="8020" --统计的总天数
 REPORT_SITE_ID		="801C" --币场ID：2为银币场
 REPORT_EARN_POINT	="801A" --坐标点数列表（纵坐标盈利数额）
 SILVER_HAND_SUM		  ="204E" --坐标点数列表（纵坐标盈利数额）

--SNS
 IS_FRIEND			="4020"--bool 是否是好友
 I_CONCERN_HIM		="4021"--bool 我是否关注他
 MESSAGE_ID			="5040"--string 私信id
 SOURCE_UID			="5041"--string 私信发送方用户id
 SOURCE_USERNAME		="5042"--string 私信发送方用户名
 DST_UID				="5043"--string 私信接收方用户id
 DST_USERNAME		="5044" --string 私信接收方用户名
 MESSAGE_TYPE		="5045"--string 私信类型
 MESSAGE_STATUS		="5046"--string 私信状态
 MESSAGE_CONTENT		="5047" --string 私信内容
 MESSAGE_NUM			="5048"--int 消息数量

 BUY_MOD_TIME		="4004"
 BUY_CHARGE_NUMBER	="5006"
 BUY_TRANS_MONEY		="5016"

 CHARGE_RESULT		="A01E"
 CHARGE_MESSAGE		="A01F"

 USE_PROPS_RESULT	="A024"
 USE_PROPS_MESSAGE	="A025"

 BUYCOINLIST_ID		="A030"
 BUYCOINLIST_INFO	="A031"
 BUYCOINLIST_COIN	="A032"
 BUYCOINLIST_PICURL	="A033"

 REMAIN_NUM             ="A038"
 INIT_NUM               ="A039"
 P_VIP_LEVEL            ="9005"
 STORE_GOODS_IS_NEW     ="A026"
 GOODS_GROUP     ="A00C"

 GOODS_CONFIG_STATUS	="5103"	--配置状态
 GOODS_SILVER_PRICE	="A017"	--配置价格
 GOODS_POINT_PRICE	="A018"	--积分价格
 GOODS_GOLD_PRICE	="A019"	--金币价格
 GOODS_PROPS_NUM4	="A014"	--道具4价格
 GOODS_PROPS_ID5		="A015"	--道具5ID
 GOODS_PROPS_NUM5	="A016"	--道具5数量
 GOODS_DEBAO_PRICE	="A01A"	--德堡币价格
 GOODS_PROPS_NUM2	="A010"	--道具2数量
 GOODS_PROPS_ID3		="A011"	--道具3ID
 GOODS_PROPS_NUM3	="A012"	--道具3数量
 GOODS_PROPS_ID4		="A013"	--道具4ID
 GOODS_GOODS_PIC		="A021"	--商品图片ID
 GOODS_DESC	="A01B"	--商品描述
GOODS_TYPE              ="A027"	--商品类型
 GOODS_PROPS_ID2		="A00F"	--道具2ID
 GOODS_PROPS_NUM1	="A00E"	--道具1数量
 GOODS_PROPS_ID1		="A00D"	--道具1ID
 GOODS_GOODS_NAME	="A00B"	--商品名称
 GOODS_GOODS_ID		="A00A"	--商品ID
 GOODS_GOODS_STATUS	="A01C"	--商品状态

 MYGOODS_PROPS_DEADLINE	="A009"	--道具5数量
 MYGOODS_DEBAO_SITE		="A008"	--德堡币价格
 MYGOODS_PROPS_PROPS_DENO="A007"	--道具2数量
 MYGOODS_PROPS_PROPS_NAME="A003"	--道具3ID
 MYGOODS_PROPS_PROPS_DESC="A004"	--道具描述
 MYGOODS_PROPS_PROPS_GROUP="A002"	--道具3数量
 MYGOODS_PROPS_PROPS_ID	="A001"	--道具4ID
 MYGOODS_GOODS_PROPS_PIC	="A020"	--商品图片ID
 MYGOODS_GOODS_PROPS_NUM ="A022"	--商品描述
 MYGOODS_GOODS_PROPS_USAGE ="A040"	--商品用途

 GOLD_HAND_SUM 	          ="204D"--金币场手数
 BONUS                     ="30A0"
 GAIN_INFO                 ="30A1"

 LABLE_NAME                 ="6019"
 LABLE_ID                 ="601A"
 LABLE_LEVEL                 ="601B"
 NEWPLAYER_VISIBLE                 ="601C"
 FATHER_LABEL_ID                 ="601D"
 SPECIAL_TAG                 ="601E"

-- /*activity*/
LOGIN_LOTTERY_GOODS_ID ="3040"
LOGIN_LOTTERY_TIMES ="700C"
LOGIN_LOTTERY_REWARD_NUM= "503A"
LOGIN_AD_IMAGE ="701E"

--happyHour转盘抽奖
HAPPYHOUR_NAMES             ="TITLE"
HAPPYHOUR_CHANCE            ="CHANCE"
HAPPYHOUR_ADIMG             ="ADIMG"
HAPPYHOUR_ADIMGNEW          ="ADIMGNEW"
HAPPYHOUR_PRIZEPST          ="PLISTIMG"
HAPPYHOUR_PRIZEIMG          ="PRIZEIMG"
HAPPYHOUR_RULES             ="RULES"

TASK_HAPPYHOUR_CON1         ="TASK"
TASK_HAPPYHOUR_CON2         ="HAPPYHOUR"

--推送信息
PUSH_USERID			="uid"
PUSH_VERSION          ="ver"
PUSH_TYPE			="type"
PUSH_MESSAGE		="message"
PUSH_SENDER			="sender"

MATCH_PLAY_TIMES      ="8022"
MATCH_WIN_TIMES       ="8023"
MATCH_WIN_CHIPS       ="8024"
MATCH_RANK_DISTRIBUTED="8025"

--支付宝充值商品列表
 ZBF_GOODS_ITEM_ID		="A030"	--道具1ID
 ZBF_GOODS_ITEM_NAME		="A031"	--商品名称
 ZBF_GOODS_ITEM_PRICE	="A032"	--商品ID
 ZBF_GOODS_ITEM_IMAGE	="A033"	--商品状态

 BOARDCAST_CONTENT="B021" --广播内容
 FINAL_SIGNIN_DATE ="7038"
 SIGNIN_TIMES ="7039"

 REG_CHANNEL 		="401A" --登录方式

 RANK_DRIFT            ="4059" --排行趋势

 FIRSTLOGIN            ="FIRSTLOGIN"

 ADVERTISEMENT_ACTION="702B"


-- Rush牌桌

RUSH_CLIENT_IP             ="2061"
RUSH_TABLE_CONFIG_ID       ="2082"
RUSH_CLIENT_BUY_CHIPS      ="2090"
RUSH_PLAYER_ID             ="2086"
RUSH_PRE_BUY_CHIPS         ="309A"
RUSH_MY_TABLELIST          ="2088"

CHAT_TYPE					="4070"

SNG_USER_STATUS				="USER_STATUS"
SNG_START_TIME				="START_TIME"
SNG_CUR_UNUM				="CUR_UNUM"


-- 收藏牌局列表


REPLAY_NAME           ="6012"
REPLAY_FID            ="6014"
REPLAY_TIME           ="4016"

-- 收藏牌局Json

 MSG_ARRAY ="A3"    --指令集合
 MSG_COMMAND_ID="17" --指令ID
 TABLE_INFO_REPLAY               ="A1"		--'1008'; -- hash(dict)  牌桌信息
 PLAYER_LIST_REPLAY              ="A2"		--'2001'; -- array(list) 玩家清单
 TABLE_ID_REPLAY                 ="A4"		--'1002'; -- string      牌桌id
 TABLE_NAME_REPLAY               ="A5"		--'1007'; -- string      牌桌名称
 TABLE_TYPE_REPLAY               ="A6"		--'1003'; -- integer     牌桌类型
 SEAT_NUM_REPLAY                 ="A7"		--'2002'; -- integer     座位数
 PAY_TYPE_REPLAY                 ="A8"		--'3026'; -- string      支付类型
 HAND_ID_REPLAY                  ="A9"		--'2006'; -- integer     这一手的id（每一手都会有唯一的id）
 PLAY_TYPE_REPLAY		= "10"	--'30A5'; -- Number      比赛类型
 SEAT_NO_REPLAY                  ="11"		--'200F'; -- integer     座位编号
 USER_ID_REPLAY                  ="12"		--'2003'; -- integer     用户id
 USER_NAME_REPLAY                ="13"		--'2004'; -- string      用户名
 USER_CHIPS_REPLAY               ="14"		--'2005'; -- integer     用户筹码
 IS_TRUSTEE_REPLAY               ="15"		--'2026'; -- boolean     是否托管
 PLAYER_STATUS_REPLAY            ="16"		--'2011'; -- string      玩家状态
 BUTTON_NO_REPLAY                ="18"		--'2013'; -- integer     庄家位置
 SBLIND_NO_REPLAY                ="19"		--'2014'; -- integer     小盲位置
 BBLIND_NO_REPLAY                ="20"		--'2015'; -- integer     大盲位置
 SMALL_BLIND_REPLAY              ="21"		--'2008'; -- integer     小盲
 BIG_BLIND_REPLAY                ="22"		--'2009'; -- integer     大盲
 BLIND_INFO_REPLAY               ="23"		--'1005'; -- array(list) 盲注信息
 TOTAL_POT_REPLAY                ="24"		--'202A'; -- integer     底池总额
 POCKET_CARDS_REPLAY             ="25"		--'201C'; -- array(list) 手牌
 COMMUNITY_CARDS_REPLAY          ="26"		--'200B'; -- array(list) 公共牌
 BET_CHIPS_REPLAY                ="27"		--'200C'; -- integer     下注（加注）筹码数
 PRIZE_LIST_REPLAY               ="28"		-- '2019'; -- array(list) 派奖list
 CARD_LIST_REPLAY                ="29"		--'2018'; -- array(list) 牌的列表，亮牌的时候用
 POT_INFO_REPLAY                 ="30"		--'200A'; -- array(list) 奖池信息
 RAKE_INFO_BF_FLOP_REPLAY        ="31"		--'2039'; -- hash(dict)  翻牌前抽水信息
 PUNISH_BLIND_INFO_REPLAY        ="32"		--'203C'; -- hash(dict)  惩罚盲注信息
 ANTE_INFO_REPLAY                ="33"		--'201F'; -- array(list) 玩家下的底注信息

 CARD_TYPE_REPLAY                ="34"		--'2020'; -- integer     牌型
 WIN_CHIPS_REPLAY                ="35"		--'2022'; -- integer     赢得的筹码数
 PUNISH_BLIND_CHIPS_REPLAY       ="36"		--'203E'; -- integer     惩罚盲注大小

 SHOWDOWN_TYPE_REPLAY            ="37"		--'202C'; -- integer     亮牌类型
 RAKE_CHIPS_AF_FLOP_REPLAY       ="38"		--'2045'; -- integer     翻牌后该玩家抽水筹码数
 MAX_CARD_REPLAY                 ="39"		--'2021'; -- array(list) 最大的牌
 RAKE_CHIPS_BF_FLOP_REPLAY       ="40"		--'2044'; -- integer     翻牌前该玩家抽水筹码数
 NEW_BLIND_CHIPS_REPLAY           ="41"     --'2030'新手盲

 REPLAY_FLOP_CARD_MSG="翻牌"
 REPLAY_TURN_CARD_MSG="转牌"
 REPLAY_RIVER_CARD_MSG="河牌"
 REPLAY_SHOWDOWN_MSG="亮牌"
 REPLAY_POT_MSG="奖池变动"
 REPLAY_PRIZE_MSG="牌局派奖"
 REPLAY_TABLE_ANTE_MSG="下前注"
 REPLAY_TABLE_BLIND_MSG="下盲注"
 REPLAY_PUNISH_BLIND_TO_BET="新手盲"
 REPLAY_PUNISH_BLIND_NO_BET="惩罚盲"

 REPLAY_TABLE_RAKE_BF_FLOP_MSG="抽水"
 REPLAY_POCKET_CARD           ="发手牌"

 REPLAY_CALL_MSG="跟注"
 REPLAY_RAISE_MSG="加注"
 REPLAY_FOLD_MSG="弃牌"
 REPLAY_CHECK_MSG="看牌"
 REPLAY_ALL_IN_MSG="全下"
 REPLAY_TABLE_BUTTON_MSG="设置庄家位"

 TABLE_ANIMATE = "牌桌互动"
 CREATE_ROOM_6HOUR = "6小时开房卡"
 SMALL_HORN = "小喇叭"
 CREATE_ROOM_STANDARD = "标准开房卡"
 CREATE_ROOM_NO_FEE = "免服务费开房卡"
 CREATE_ROOM_DIY = "自定义开房卡"
 CREATE_MATCH_DIY_SNG = "自定义SNG卡"
 CREATE_MATCH_DIY_MTT = "自定义MTT卡"
 -- CREATE_ROOM_6Plus = "6+测试开房卡"
 CREATE_ROOM_6Plus = "6+大牌扑克牌局卡"
